"""
Marketing-focused reporting for executive summaries and ROI analysis.

Features:
- Executive dashboards
- ROI calculations
- Business impact metrics
- Success stories
- Comparison benchmarks
"""

from typing import Dict, Any, List, Optional
from datetime import datetime
import json


class MarketingReporter:
    """Generate marketing materials and executive summaries."""

    def __init__(self, company_name: str = "Your Company"):
        self.company_name = company_name

    def generate_executive_summary(
        self,
        summary: Dict[str, Any],
        project_name: str = "ML Project",
        dataset_name: str = "Production Dataset"
    ) -> str:
        """
        Generate executive-friendly summary.

        Args:
            summary: Output from compute_overfit_guard_summary
            project_name: Name of the project
            dataset_name: Name of the dataset

        Returns:
            Formatted executive summary
        """
        delta = summary['delta']
        ga = summary['guard_activity']
        meta = summary['meta']

        # Calculate business metrics
        roi_data = self.calculate_roi(summary)

        report = []
        report.append("=" * 80)
        report.append(f"🎯 EXECUTIVE SUMMARY: {project_name}")
        report.append("=" * 80)
        report.append(f"\n**Dataset:** {dataset_name}")
        report.append(f"**Date:** {datetime.now().strftime('%B %d, %Y')}")
        report.append(f"**Generated by:** Overfit Guard v1.0\n")

        # Key Findings
        report.append("\n📊 KEY FINDINGS\n")
        report.append("─" * 80)

        # Model Performance
        if delta['test_metric_pct_points'] > 0:
            report.append(f"✅ **Model Accuracy:** Improved by {delta['test_metric_pct_points']:.1f}%")
        elif abs(delta['test_metric_pct_points']) < meta['accuracy_tol_pct_points']:
            report.append(f"✅ **Model Accuracy:** Maintained (no degradation)")
        else:
            report.append(f"ℹ️  **Model Accuracy:** Slight trade-off ({abs(delta['test_metric_pct_points']):.1f}%) for improved robustness")

        # Generalization
        if delta['gap_reduction_pct'] > 0:
            report.append(f"✅ **Generalization:** Enhanced by {delta['gap_reduction_pct']:.0f}%")

        # Time Savings
        if delta['epochs_saved'] > 0:
            report.append(f"⚡ **Training Time:** Reduced by {delta['time_savings_pct']:.0f}% ({delta['epochs_saved']} fewer epochs)")

        # Detection Stats
        report.append(f"🛡️  **Protection:** {ga['detections']} issues detected, {ga['corrections']} auto-corrected")

        # Business Impact
        report.append("\n\n💰 BUSINESS IMPACT\n")
        report.append("─" * 80)
        report.append(f"⏰ **Time Saved:** {roi_data['time_saved_hours']:.1f} hours per model")
        report.append(f"💵 **Cost Savings:** ${roi_data['cost_savings_usd']:.2f} per training run")
        report.append(f"🎯 **ROI:** {roi_data['roi_percentage']:.0f}% return on investment")
        report.append(f"📈 **Productivity:** {roi_data['productivity_gain']:.0f}% efficiency improvement")

        # Recommendations
        report.append("\n\n💡 RECOMMENDATIONS\n")
        report.append("─" * 80)

        if ga['detection_rate'] > 0.3:
            report.append("1. ✓ High overfitting rate detected. Consider expanding training dataset.")
        if delta['epochs_saved'] > 5:
            report.append("2. ✓ Significant time savings achieved. Scale to all models for maximum ROI.")
        if delta['gap_reduction_pct'] > 20:
            report.append("3. ✓ Strong generalization improvement. Deploy to production with confidence.")

        report.append("\n" + "=" * 80)
        report.append(f"Generated by Overfit Guard - Protecting {self.company_name}'s ML investments")
        report.append("=" * 80 + "\n")

        return "\n".join(report)

    def calculate_roi(
        self,
        summary: Dict[str, Any],
        cost_per_gpu_hour: float = 1.50,
        engineer_hourly_rate: float = 100.0,
        avg_debugging_hours: float = 4.0
    ) -> Dict[str, float]:
        """
        Calculate ROI metrics for using Overfit Guard.

        Args:
            summary: Output from compute_overfit_guard_summary
            cost_per_gpu_hour: Cloud GPU cost per hour
            engineer_hourly_rate: Engineer cost per hour
            avg_debugging_hours: Average hours spent debugging overfitting

        Returns:
            Dictionary with ROI metrics
        """
        delta = summary['delta']
        base_epochs = summary['baseline']['epochs']
        guard_epochs = summary['guard']['epochs']

        # Estimate training time saved (assuming 1 minute per epoch baseline)
        time_saved_minutes = delta['epochs_saved'] * 1.0
        time_saved_hours = time_saved_minutes / 60.0

        # GPU cost savings
        gpu_cost_savings = time_saved_hours * cost_per_gpu_hour

        # Engineer time saved (reduced debugging)
        # Assume guard prevents avg_debugging_hours of manual debugging
        engineer_time_saved = avg_debugging_hours * 0.5  # 50% reduction
        engineer_cost_savings = engineer_time_saved * engineer_hourly_rate

        # Total savings
        total_savings = gpu_cost_savings + engineer_cost_savings

        # Cost of using Overfit Guard (minimal overhead)
        overhead_cost = 10.0  # Nominal subscription cost

        # Net savings and ROI
        net_savings = total_savings - overhead_cost
        roi_percentage = (net_savings / overhead_cost * 100) if overhead_cost > 0 else 0

        # Productivity gain
        productivity_gain = (time_saved_hours + engineer_time_saved) / 8.0 * 100  # As % of workday

        return {
            'time_saved_hours': time_saved_hours + engineer_time_saved,
            'gpu_cost_savings': gpu_cost_savings,
            'engineer_cost_savings': engineer_cost_savings,
            'cost_savings_usd': total_savings,
            'overhead_cost': overhead_cost,
            'net_savings': net_savings,
            'roi_percentage': roi_percentage,
            'productivity_gain': productivity_gain,
        }

    def generate_success_story(
        self,
        summary: Dict[str, Any],
        customer_name: str = "Acme Corp",
        industry: str = "Healthcare",
        use_case: str = "Medical Image Classification"
    ) -> str:
        """
        Generate a customer success story.

        Args:
            summary: Output from compute_overfit_guard_summary
            customer_name: Name of customer
            industry: Industry vertical
            use_case: Specific use case

        Returns:
            Success story text
        """
        delta = summary['delta']
        ga = summary['guard_activity']
        roi_data = self.calculate_roi(summary)

        story = []
        story.append("=" * 80)
        story.append(f"📖 SUCCESS STORY: {customer_name}")
        story.append("=" * 80)
        story.append(f"\n**Industry:** {industry}")
        story.append(f"**Use Case:** {use_case}")
        story.append(f"**Challenge:** Overfitting in production ML models\n")

        story.append("\n🎯 THE CHALLENGE\n")
        story.append("─" * 80)
        story.append(f"{customer_name} was experiencing overfitting in their {use_case} models,")
        story.append("leading to poor generalization and unreliable predictions. Manual debugging")
        story.append("was time-consuming and expensive.\n")

        story.append("\n💡 THE SOLUTION\n")
        story.append("─" * 80)
        story.append(f"By implementing Overfit Guard, {customer_name} automated overfitting detection")
        story.append("and correction across their ML pipeline. The system integrated seamlessly with")
        story.append("their existing PyTorch/TensorFlow workflows.\n")

        story.append("\n📈 THE RESULTS\n")
        story.append("─" * 80)
        if delta['gap_reduction_pct'] > 0:
            story.append(f"• {delta['gap_reduction_pct']:.0f}% improvement in model generalization")
        if delta['epochs_saved'] > 0:
            story.append(f"• {delta['time_savings_pct']:.0f}% reduction in training time")
        story.append(f"• ${roi_data['cost_savings_usd']:.0f} cost savings per model")
        story.append(f"• {ga['detections']} overfitting issues caught automatically")
        story.append(f"• {roi_data['productivity_gain']:.0f}% productivity increase for ML team\n")

        story.append('\n💬 "Overfit Guard has transformed our ML development process."')
        story.append(f'   - ML Lead, {customer_name}\n')

        story.append("=" * 80 + "\n")

        return "\n".join(story)

    def generate_comparison_benchmark(
        self,
        results: List[Dict[str, Any]],
        dataset_names: List[str]
    ) -> str:
        """
        Generate benchmark comparison across multiple datasets.

        Args:
            results: List of summary dictionaries
            dataset_names: List of dataset names

        Returns:
            Formatted benchmark report
        """
        report = []
        report.append("=" * 100)
        report.append("📊 OVERFIT GUARD - MULTI-DATASET BENCHMARK")
        report.append("=" * 100)
        report.append("")

        # Header
        header = f"{'Dataset':<25} {'Gap Reduction':<20} {'Time Saved':<20} {'Test Δ':<15}"
        report.append(header)
        report.append("─" * 100)

        # Results
        for dataset_name, summary in zip(dataset_names, results):
            delta = summary['delta']
            gap_red = f"{delta['gap_reduction_pct']:+.1f}%"
            time_saved = f"{delta['time_savings_pct']:.0f}%"
            test_delta = f"{delta['test_metric_pct_points']:+.2f}pp"

            row = f"{dataset_name:<25} {gap_red:<20} {time_saved:<20} {test_delta:<15}"
            report.append(row)

        report.append("─" * 100)

        # Averages
        avg_gap = sum(s['delta']['gap_reduction_pct'] for s in results) / len(results)
        avg_time = sum(s['delta']['time_savings_pct'] for s in results) / len(results)
        avg_test = sum(s['delta']['test_metric_pct_points'] for s in results) / len(results)

        report.append(f"{'AVERAGE':<25} {avg_gap:+.1f}%{'':<15} {avg_time:.0f}%{'':<15} {avg_test:+.2f}pp")
        report.append("")
        report.append("=" * 100)
        report.append("")

        return "\n".join(report)

    def export_to_json(
        self,
        summary: Dict[str, Any],
        filepath: str,
        include_roi: bool = True
    ) -> None:
        """
        Export results to JSON for integration with BI tools.

        Args:
            summary: Output from compute_overfit_guard_summary
            filepath: Output file path
            include_roi: Whether to include ROI calculations
        """
        export_data = {
            'timestamp': datetime.now().isoformat(),
            'results': summary,
        }

        if include_roi:
            export_data['roi'] = self.calculate_roi(summary)

        with open(filepath, 'w') as f:
            json.dump(export_data, f, indent=2)

    def generate_slide_content(self, summary: Dict[str, Any]) -> Dict[str, str]:
        """
        Generate content for presentation slides.

        Args:
            summary: Output from compute_overfit_guard_summary

        Returns:
            Dictionary with slide titles and content
        """
        delta = summary['delta']
        ga = summary['guard_activity']
        roi_data = self.calculate_roi(summary)

        slides = {}

        # Title Slide
        slides['title'] = f"""
Overfit Guard Results
Automatic ML Overfitting Detection & Correction
"""

        # Problem Slide
        slides['problem'] = f"""
The Challenge
• Overfitting reduces model reliability
• Manual detection is time-consuming
• Production failures are costly
• {ga['detections']} overfitting events detected
"""

        # Solution Slide
        slides['solution'] = f"""
The Solution
• Automatic real-time monitoring
• Intelligent correction strategies
• Zero-code integration
• {ga['corrections']} automatic fixes applied
"""

        # Results Slide
        slides['results'] = f"""
Results
• Generalization: {delta['gap_reduction_pct']:+.0f}% improvement
• Training Time: {delta['time_savings_pct']:.0f}% reduction
• Cost Savings: ${roi_data['cost_savings_usd']:.2f} per model
• ROI: {roi_data['roi_percentage']:.0f}%
"""

        # Next Steps Slide
        slides['next_steps'] = """
Next Steps
1. Deploy to all ML pipelines
2. Monitor ROI and savings
3. Scale across organization
4. Continuous optimization
"""

        return slides
